/**
 *  sfd_gpui.h - includes for working with the gpu/gte.
 *  CC is really particular about the order of these. They don't include the
 *  headers they need, nor does the documentation say what the correct order of
 *  inclusion is. This header eliminates the headache associated with this. The
 *  correct order presented here was found through trial and error.
 *
 *  Copyright (C) 2025  SegFaultedDreams
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
#ifndef _SFD_GPU_INCLUDES_H_
#define _SFD_GPU_INCLUDES_H_

#include <sys/types.h>
#include <libgte.h>
#include <libgpu.h>
#include <libgs.h>
#include <libetc.h>

#endif /* _SFD_GPU_INCLUDES_H_ */
